---
#
# Playbook to install nagios server, clients and
# generate service checks based on Ansible inventory
#


# role for nagios clients via NRPE
- hosts: dolly01
#  remote_user: "{{ ansible_system_user }}"
  tasks:
    - name: Include OS-specific variables.
      include_vars: "defaults/main.yml"
  roles:
    - { role: nagios_client }
    - { role: firewall_client, when: manage_firewall_client|bool }
