---
#
# Playbook to update templates on nagios host server
# and restart nagios master server
  
# role for nagios server
- hosts: nagios
#  remote_user: "{{ ansible_system_user }}"
  tasks:
    - name: Include OS-specific variables.
      include_vars: "defaults/main.yml"
  roles:
    - { role: nagios }
    - { role: firewall, when: manage_firewall|bool }
    - { role: instructions }
